config:
  target: "https://www.google.com"
  phases:
    - duration: 60         # Run test for 60 seconds
      arrivalRate: 5       # 5 users per second

scenarios:
  - flow:
      - get:
          url: "/"
          name: "Load Google Home"
